"""add_phase5_fields

Revision ID: 6d9a46c7da96
Revises: a2fff07ed550
Create Date: 2026-09-22 05:37:57.423841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9a46c7da96'
down_revision: Union[str, Sequence[str], None] = 'a2fff07ed550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('matched_rule_id', sa.String(), nullable=True))
    op.add_column('actions', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('approvals', sa.Column('fingerprint', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('status', sa.String(), server_default='PUBLISHED', nullable=False))
    op.add_column('policies', sa.Column('published_at', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('created_by', sa.String(), server_default='system', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'created_by')
    op.drop_column('policies', 'published_at')
    op.drop_column('policies', 'status')
    op.drop_column('approvals', 'fingerprint')
    op.drop_column('actions', 'evidence')
    op.drop_column('actions', 'matched_rule_id')
    # ### end Alembic commands ###
